import { defineConfig } from "vite";

// One ES module out per browser module in, under static/dist/, which is what
// index.html loads and what the jsdom page tests import. Fixed file names, no
// content hashes: index.html is served as a static file by app.py rather than
// generated by Vite, so the names in its <script> tags have to stay stable.
//
// The output is minified for asset size and cacheability only. It is not an
// obfuscation or security measure — minified JavaScript is trivially readable,
// and this bundle is a small fraction of the WASM payload that later slices
// will ship anyway.
export default defineConfig({
  build: {
    outDir: "static/dist",
    emptyOutDir: true,
    minify: "esbuild",
    target: "es2022",
    rollupOptions: {
      // Each module registers itself with the shell at load time and none of
      // them imports another, so these are five independent entry points rather
      // than one bundle with an entry.
      input: Object.fromEntries(
        ["shell", "sudoku", "queens", "killer", "pwa"].map((name) => [
          name,
          `web/${name}.ts`,
        ]),
      ),
      output: {
        format: "es",
        entryFileNames: "[name].js",
        chunkFileNames: "[name].js",
        // The Sudoku engine is shared by the sudoku and killer tabs — Killer is
        // part of that context, not a separate one (ADR 0002) — so it ships as
        // one chunk both entries import rather than being inlined into each.
        // Named here because the default name is whichever of its modules
        // rollup happened to enter through, which says nothing useful.
        manualChunks: (id) =>
          id.includes("/web/sudoku/") ? "sudoku-engine" : undefined,
      },
    },
  },
});
