import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

// One ES module out, under static/dist/, which is what index.html loads and
// what the jsdom page tests import. A fixed file name, no content hash:
// index.html is served as a static file by app.py rather than generated by
// Vite, so the name in its <script> tag has to stay stable.
//
// The output is minified for asset size and cacheability only. It is not an
// obfuscation or security measure — minified JavaScript is trivially readable,
// and this bundle is a small fraction of the WASM payload that later slices
// will ship anyway.
export default defineConfig({
  plugins: [preact()],
  build: {
    outDir: "static/dist",
    emptyOutDir: true,
    minify: "esbuild",
    target: "es2022",
    rollupOptions: {
      input: { app: "web/app.tsx" },
      output: {
        format: "es",
        entryFileNames: "[name].js",
        chunkFileNames: "[name].js",
        // One file: the share handoff and the puzzle tabs share module state
        // (web/ui/shared-reading.ts), so splitting them into separate entries
        // would give each its own copy of it and quietly break the handoff.
        inlineDynamicImports: true,
      },
    },
  },
});
